name: 功能建议
description: 添加全新功能或改进现有功能
title: "[Enhancement] "
labels: ["enhancement"]

body:
  - type: checkboxes
    id: searched
    attributes:
      label: 已经搜索过 Issues
      description: 请确认你已经在 Issues 中搜索过，未发现重复
      options:
        - label: 我已经搜索过 Issues，没有发现重复
    validations:
      required: true

  - type: textarea
    id: feature
    attributes:
      label: 功能描述
      description: 请详细描述你希望添加或改进的功能
      placeholder: 请描述你想要的功能
    validations:
      required: true

  - type: textarea
    id: scenario
    attributes:
      label: 使用场景
      description: 请说明该功能在什么场景下使用，以及为什么需要它
      placeholder: 请描述典型使用场景
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: 其他补充
      description: 如果你有额外信息，请在此填写
      placeholder: 可选

  - type: checkboxes
    id: pr
    attributes:
      label: 是否愿意提交 PR 实现当前 Issue
      options:
        - label: 我愿意尝试提交 PR